keys:
  - &users:
    - &as age1qayyp9sggvkgguhgwx72ymn2jev56nrrrf9p53uslt6y6nvg4uqs5v767m
  - &hosts:
    - &babar age1yzukf92xvxq9exl692wtuxpfc6hjgzytvpc2qfj6r4y7dmvrmd2suxsyfz
    - &musclor age1n76tzqpghjc8m54x9v66qpat3zwm64sw9xa8adq39fcumy4r6ynqw9zdhr
    - &popeye age122drj0k8kyelzx54ekwqjudzx5qumc53pw9lpnyvv6h44wxhs3wq5ptw05
    - &becassine age1rpddtqhpr25p2uvwca2uf7v8xnfyyc57vdfystt6tepaxfmc5uzs8l3drx
creation_rules:
  - path_regex: nix/home/work/secrets.yaml
    key_groups:
      - age:
          - *as
  - path_regex: nix/home/as-tui/secrets.yaml
    key_groups:
      - age:
          - *as
  - path_regex: nix/nixos/babar/secrets.yaml
    key_groups:
      - age:
          - *as
          - *babar
  - path_regex: nix/nixos/musclor/secrets.yaml
    key_groups:
      - age:
          - *as
          - *musclor
  - path_regex: nix/nixos/popeye/secrets.yaml
    key_groups:
      - age:
          - *as
          - *popeye
  - path_regex: nix/nixos/becassine/secrets.yaml
    key_groups:
      - age:
          - *as
          - *becassine
