#!/usr/bin/env bash
# remote_install <machine conf> <key directory>
set -Eeuo pipefail

MACH="${1:-}"
KEYDIR="${2:-}"
[ -n "$MACH" ] || (echo Remote machine configuration not specified >&2; exit 1)
[ -d "$KEYDIR" ] || (echo Key directory $KEYDIR does not exist >&2; exit 1)

# Create a temporary directory
temp=$(mktemp -d)

# Function to cleanup temporary directory on exit
cleanup() {
  rm -rf "$temp"
}
trap cleanup EXIT

# Create the directory where sshd expects to find the host keys
install -d -m755 "$temp/etc/ssh"

cp "$KEYDIR"/ssh_host_ed25519* "$temp/etc/ssh"

# Set the correct permissions so sshd will accept the key
chmod 600 "$temp/etc/ssh/ssh_host_ed25519"

# Install NixOS to the host system with our secrets
nix run github:nix-community/nixos-anywhere -- -i ~/.ssh/id_ed25519_as \
  --extra-files "$temp" --flake ".#$MACH" root@clochette.local
