name: "Build packages"

env:
  EXTRA_NIX_CONFIG: |
    auto-optimise-store = true
    experimental-features = nix-command flakes

on:
  push:
    paths:
      - 'nix/packages/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ env.EXTRA_NIX_CONFIG }}
    - uses: cachix/cachix-action@v14
      with:
        name: bambi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build packages
      run: |
        echo "🔨 Starting build for packages..."
        nix build .#deploy-rs .#filebrowser-quantum .#nix-sweep
        exit $?
    - name: Push to Cachix
      run: |
        cachix push bambi ./result*
